### ISSUE TITLE
transfer request

### ISSUE THREAD

**Issue by steveoh** [agrc/dabs-skid#1]
this seems like a good repo to transfer to the agrc org rather than fork it back. is there a specific reason you'd like to keep this in eneemann?

**Comment by eneemann** [comment]
No, you're right, we could just transfer this one.

**Comment by eneemann** [comment]
@steveoh per [GitHub Docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) it says "To transfer repositories to an organization, you must have repository creation permissions in the receiving organization"

**Comment by eneemann** [comment]
![image](https://github.com/eneemann/dabs-skid/assets/38330621/dce20a07-1943-43ae-ac10-ab70b6ef3c1a)

**Comment by steveoh** [comment]
yeah, we kicked you out. I've added you back temporarily. You should see an invite.

**Comment by eneemann** [comment]
Yep, I knew you did.  The deed should be done now.
